vich_uploader:
    db_driver: orm # Set to 'mongodb' if you're using MongoDB

    metadata:
        type: attribute # Use 'annotation' if you are using annotations

    mappings:
        post_thumbnail:
            uri_prefix: '/images/post/'
            upload_destination: '%kernel.project_dir%/public/images/post'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true
